= ML Workbench Glossary

This page serves as a glossary for the terms used in the ML Workbench documentation.

For a general TigerGraph glossary, see the xref:tigergraph-server:reference:glossary.adoc[TigerGraph Server Glossary].

For further details about specific KubeFlow or Kubernetes services, see their respective documentation sites at:

* https://www.kubeflow.org/docs/started/[KubeFlow]
* https://kubernetes.io/docs/home/[Kubernetes]


== AutoML

A general term for research and projects with the goal of automating the process of creating a machine learning model from the source data.

== InferenceService

== Katib

An open-source AutoML project that enables hyperparameter tuning across many languages and Machine Learning frameworks.
Katib is the core of the Experiments (AutoML) tab in ML Workbench.

For more information, see link:https://www.kubeflow.org/docs/components/katib/overview/[the official Katib documentation.]

== Kubeflow

== Kubernetes

== KServe

== Model Serving

The process of turning a trained Machine Learning model into a service that can accept queries sent to it.

For example, a trained image classification model could be set up with Model Serving to receive an image as an API request and return its classification.

== Notebook

An interactive application for programming, annotating and sharing code, often used for machine learning.
Notebooks support text formatting, embedded images, code blocks and console output.

== PVC

A PeristentVolumeClaim, or user-accessible storage in a Kubernetes cluster. See link:https://kubernetes.io/docs/concepts/storage/persistent-volumes/[the official documentation] for more details.

== pyTigerGraph

A Python package for connecting to TigerGraph databases.
See the full xref:pytigergraph:intro:index.adoc[the pyTigerGraph documentation] for further details.

== TensorBoard

A live visual dashboard that updates in real time to show the progress of model training.
