= Frequently Asked Questions (FAQ)

== Does ML Workbench need to be configured differently for a TigerGraph database instance on a cluster?
No. Whether your TigerGraph database instance is set up on a single machine or on a cluster, the setup process for ML Workbench is the same.

== Can I use ML Workbench to train a graph neural network (GNN) using a GPU?
Yes. ML Workbench supports both CPU and GPUs for training a GNN.

== Can I use a 3rd party ML Framework to train a GNN?
Yes. ML Workbench is compatible with some of the most popular Graph ML frameworks such as PyTorch Geometric and DGL.

==  Does Workbench offer in-DB GNN training?
No. Training happens outside the TigerGraph database.
This means that data is being exported to your ML Development environment and the model training is happening at your development environment using your infrastructure.
Our team is actively working on bringing GNN training and inference into TigerGraph itself.

==  I have TigerGraph DB set up with AWS. Would ML Workbench still work with a 3rd party Cloud provider?
Yes. ML Workbench is compatible with TigerGraph database setups both on your own on-prem servers and with a 3rd party cloud such as AWS or GCP.
The GDPS component must be deployed onto the same server as the TigerGraph database for ML Workbench to be able to communicate with your database instances.

==  Does ML Workbench work with TigerGraph Cloud?
Yes. ML Workbench works with your TigerGraph Cloud instances. You can simply make a connection to your cloud instances by providing the login credentials.

==  The data set used in your Cora example notebooks forms a homogeneous graph. Can we train GNN using heterogeneous graph data?
Yes. With the ML Workbench V1 GA release, we now support GNN training on a heterogeneous graph. Please check out our examples using the IMDB data set.

==  Can I leverage the existing algorithms in the Graph Data Science Library to generate graph features that would be appropriate for GNN training?
Yes. You can directly leverage our existing graph algorithms or customize your own features and export them for GNN training.
Please note that these features will need to be pre-populated prior to loading to your ML development pipelines.

== Can I use a password instead of a token to log in to JupyterLab?

Yes. With the token, you can set a password for JupyterLab.

Log out from JupyterLab and you will see the page to set a password with your token.
After setting the password, restart JupyterLab for the change to take effect.

If you are running Jupyter lab inside a Docker container, you can restart the container by running the command `docker restart <Container ID>`.

== Can I install pyTigerGraph on a Mac with an M1 processor?

Yes. You can install pyTigerGraph as normal by running `pip install pyTigerGraph` or  `pip install pyTigerGraph[gds]`. Use a `pip` version of v21 or later.