= Deploy GDPS to TigerGraph Server
:experimental:
:description: Instructions for deploying Graph Data Processing Service to a TigerGraph server.

Deploying Graph Data Processing Service (GDPS) on the TigerGraph Server allows the ML Workbench to communicate with the server.
This gives you access to the graph data stored in your TigerGraph database from the Workbench and develop Graph Neural Network (GNN) models with production scale graph data.

Our JupyterLab extension that comes with the Workbench offers a server manager feature that allows you to deploy GDPS through a web interface.
If you are using your own JupyterLab-based IDE, you'll need to xref:getting-started:jupyterlab.adoc[install the ML Workbench JupyterLab extension] before going through this guide.

NOTE: If you don't want to use JupyterLab as your IDE, or if you are using a version JupyterLab that's older than 3.0, see xref:advanced-setup.adoc[] for instructions to deploy GDPS manually.

== Prerequisites
* TigerGraph ML Workbench installed on your machine.
* A running TigerGraph instance with port 8000 accessible by the server running the ML Workbench.
For a TigerGraph cluster, only port 8000 on the m1 machine needs to be accessible.

== Procedure

. From your terminal, run `jupyter lab`.
This takes you to the JupyterLab server in your browser.
On the left pane of the page, click the TigerGraph logo to open the server manager.
. Click btn:[Add Server] and fill in the relevant server and host information.
* Server IP is the IP address of the TigerGraph server.
If you are connecting to a cluster, provide the IP address of the m1 machine of the cluster.
* Host OS is the OS of the host machine that is running the database. If the database is running in a container, it is the OS of the machine that hosts the container, not the OS inside the container.
* GDPS port is the port to serve the Graph Data Processing Service (GDPS).
. Click btn:[Submit].
This adds a server to the list of servers in the server manager.
. Click btn:[GDPS] on the server you just added.
If there is no GDPS running on the database server, you will be prompted to install GDPS on the server.
Follow the prompts to provide the necessary information about the server to install GDPS.
After the installation is complete, your Workbench is now able to connect to the TigerGraph server, and you are ready to start using your graph data to develop GNN models.

== Next steps

With the TigerGraph server connected to the Workbench, you are ready to start working through the xref:tutorials:index.adoc[tutorials] and xref:tutorials:index.adoc#_train_your_first_model[train your first model].
