= Install TigerGraph ML Workbench
:description: Instructions for installing the ML Workbench

This page provides the instructions to install TigerGraph ML Workbench.

== Prerequisites
* Supported OS: macOS and Linux
* Port 8888 needs to be open on the machine hosting the Jupyter server to access JupyterLab.

== Procedure

. link:https://www.tigergraph.com/ml-workbench/[Download] the installation bash script from https://www.tigergraph.com/ml-workbench.
Choose the version of the package based on your OS.
. Run the installation script.
In your terminal, run `bash <path_to_installation_script>`.
You will be asked to review the terms and conditions, as well as choose a location to install the workbench.
. Close the current shell session.
In a new terminal tab, run `jupyter lab` to start the jupyter lab server.
You will see a URL you can use to visit the server in a browser. Or if you would like to access jupyter lab from a remote browser, run `jupyter lab --ip=0.0.0.0 --no-browser` instead.

== Video walk-through
Here is a video walk-through of the installation process:

video::7vnxNPWxoVQ[youtube,start=262,width=700,heigh=400]


== Next steps

* xref:deploy-gdps.adoc[Connect your Workbench to a TigerGraph server]