= Install UDFs

After the client-side ML Workbench setup is complete, the next step is to install a set of User Defined Functions (UDFs) to your TigerGraph database instances.
These UDFs are prerequisites for some of the ML Workbench core functionality.

Both of the required UDFs can be installed with our UDF installer function from pyTigerGraph.

[NOTE]
The installer function will attempt to append the pyTigerGraph UDFs to any existing UDFs in the TigerGraph database, preserving user-created UDFs.
Even so, it is recommended to back up existing UDFs before installation.

== UDFs for the Graph Data Science library
If you are planning to run any graph algorithms from our Graph Data Science library for graph feature engineering, follow the “UDF for built-in Graph Algorithms” section in link:https://github.com/TigerGraph-DevLabs/mlworkbench-docs/blob/main/tutorials/basics/2.1_UDF_installer.ipynb[this tutorial].

== UDFs for the dataloader
One of the key functionality of the  ML Workbench is the ability to export your connected data set stored in the TigerGraph database to your ML development environment and to transform your connected data set to be compatible with other popular ML frameworks such as pyTorch.
Please follow the “UDF for dataloader” section in link:https://github.com/TigerGraph-DevLabs/mlworkbench-docs/blob/main/tutorials/basics/2.1_UDF_installer.ipynb[this tutorial].

[NOTE]
====
There are two versions of the UDF dataloader:

* ML Workbench Developer Edition
* ML Workbench Enterprise Edition

The Enterprise edition of the dataloader has added capability to stream large data sets over a Kafka cluster.
====
The tutorial contains the link to the UDF for the Developer Edition, and if you are interested in the Enterprise Edition of ML Workbench, please contact our sales team at tgsales@tigergraph.com
