= Get started with ML Workbench Sandbox Image
:sectnums:
:description: This page provides instructions on running the ML Workbench from a sandbox Docker image.

This page walks you through running the TigerGraph ML Workbench in a Docker container.

To help you get started quickly, we provide a “sandbox” docker image that has the TigerGraph database, GDPS, and ML Workbench pre-installed.
The “Cora” dataset used for tutorials is also preloaded into the database.

== Prerequisites
* You machine needs to meet the xref:tigergraph-server:installation:hw-and-sw-requirements.adoc[].
** Make sure you are allocating enough CPU and memory to your Docker containers.
It is recommended that you allocate at least 8 CPUs and 16 GB of memory to your Docker containers.
* Docker Desktop is running on your machine.

== Procedure

Run the following command to pull the Workbench image, bind ports, map a shared data folder, and start a container from the image

[.wrap,console]
----
$ docker run -it -p 14022:22 -p 8000:8000 -p 8888:8888 -p 9000:9000 -p 14240:14240 -p 6006:6006  --name tgsandbox --ulimit nofile=1000000:1000000 -v ~/tgsandbox:/home/tigergraph/tgsandbox tigergraphml/sandbox
----

Here is a breakdown of the options in the docker run command above

* `-it`: run the container interactively and allocate a pseudo-TTY.
* `-p`: map a port of the host (14022) to a port of the container (22).
* `--name`: name of the container. Can be any name you like.
* `--ulimit`: the limit of number of open file descriptors per process.
* -v: mount a folder on the host (`~/tgsandbox`) to a folder in the container (`/home/tigergraph/tgsandbox`).
This allows you to keep your files after the container is removed.
If you are using Windows, change the path using Windows file system conventions.
For example, `c:\tgsandbox instead of ~/tgsandbox`.

After the container has started up, go to the URL in your terminal to access the JupyterLab IDE.

== Video walk-through
Here is a video walk-through of running the sandbox image:

video::7vnxNPWxoVQ[youtube,width=600,height=400]


== Next steps

* xref:tutorials:index.adoc#_train_your_first_model[Train your first model].