= Get started with ML Workbench Sandbox Image
:sectnums:
:description: This page provides instructions on running the ML Workbench from a sandbox Docker image.
:page-aliases: docker.adoc

This page walks you through running the TigerGraph ML Workbench in a Docker container.

To help you get started quickly, we provide a “sandbox” Docker image that has the TigerGraph database, GDPS, and ML Workbench pre-installed.
The link:https://graphsandnetworks.com/the-cora-dataset/[“Cora” dataset] and the link:https://www.imdb.com/interfaces/[IMDB datasets] used for tutorials are also preloaded into the database.

Use this link to download Docker if needed: link:https://docs.docker.com/get-docker/[Get Docker]

== Prerequisites
* You machine meets the xref:tigergraph-server:installation:hw-and-sw-requirements.adoc[].
** Make sure you are allocating enough CPU and memory to your Docker containers.
TigerGraph recommends allocating at least 8 CPUs and 16 GB of memory.
* Docker Desktop is running on your machine.

== Procedure

. Run the following command to pull the Workbench image, bind ports, map a shared data folder, and start a container from the image
+
[.wrap,console]
----
docker run -it -p 14022:22 -p 8888:8888 -p 9000:9000 -p 14240:14240 -p 6006:6006  --name tgsandbox --ulimit nofile=1000000:1000000 -v ~/tgsandbox:/home/tigergraph/tgsandbox/save tigergraphml/sandbox:1.0.0
----
+
--
Here is a breakdown of the parameters in the previous command:

* `-it`: run the container interactively and allocate a pseudo-TTY.
If you'd rather run the container non-interactively, use `-d` instead.
You can use `docker logs` to retrieve the URL for JupyterLab.
* `-p`: map a port of the host (14022) to a port of the container (22).
** Port 22: SSH server
** Ports 9000 and 14240: TigerGraph database
** Port 8000: GDPS
** Port 8888: ML Workbench
** Port 6006: Tensorboard.
* `--name`: name of the container.
The command sets the name to `tgsandbox`, but you can change this to another name.
* `--ulimit`: the limit of number of open file descriptors per process.
* `-v`: mount a folder on the host (`~/tgsandbox`) to a folder in the container (`/home/tigergraph/tgsandbox`).
These two folders are synced and hence allow you to save any file even after the container is removed.
However, the folder on the host (`~/tgsandbox`) has to be writable by the user inside the container.
Normally, this can be ensured by making the folder public, e.g., `chmod 777  ~/tgsandbox`.
If you are using Windows, change the path using Windows file system conventions.
For example, `C:\tgsandbox` instead of `~/tgsandbox`.
--
+
This command prints the link to the JupyterLab workbench in a format similar to `127.0.0.1:8888/lab?token=`. Use this link in your browser to access the workbench, which is a customized version of JupyterLab.

[NOTE]
If the Docker container is running remotely, open port 8888 on the remote machine to allow the connection. Then replace `127.0.0.1` in the returned address with the remote machine IP address.

. If you want shell access to your Docker container, run the following command:
+
[.wrap,console]
----
$ ssh -p 14022 tigergraph@localhost
----
When prompted for the password for user `tigergraph`, enter `tigergraph`.
+
Alternatively, if you don't have access to `ssh`, you can get shell access through `docker exec`:
+
[.wrap,console]
----
$ docker exec -it $(docker ps | grep tgsandbox | awk '{print $1}') /bin/sh
----
. If you turn off the sandbox container and start the container again, JupyterLab starts automatically as soon as the container starts.
However, JupyterLab generates a new token everytime it restarts.
You can retrieve the URL with the token by running `docker logs tgsandbox`, or click the container in the Docker Desktop UI to retrieve the URL from the latest terminal output.


== Video walk-through
Here is a video walk-through of running the sandbox image:

video::7vnxNPWxoVQ[youtube,width=700,height=400]


== Next steps

* xref:tutorials:index.adoc[Train your first model] by following the tutorials.