= Get started with ML Workbench Sandbox Image
:sectnums:
:description: This page provides instructions on running the ML Workbench from a sandbox Docker image.
:page-aliases: docker.adoc

This page walks you through running the TigerGraph ML Workbench in a Docker container.

To help you get started quickly, we provide a “sandbox” docker image that has the TigerGraph database, GDPS, and ML Workbench pre-installed.
The “Cora” dataset used for tutorials is also preloaded into the database.

== Prerequisites
* You machine needs to meet the xref:tigergraph-server:installation:hw-and-sw-requirements.adoc[].
** Make sure you are allocating enough CPU and memory to your Docker containers.
It is recommended that you allocate at least 8 CPUs and 16 GB of memory to your Docker containers.
* Docker Desktop is running on your machine.

== Procedure

Run the following command to pull the Workbench image, bind ports, map a shared data folder, and start a container from the image

[.wrap,console]
----
$ docker run -it -p 14022:22 -p 8000:8000 -p 8888:8888 -p 9000:9000 -p 14240:14240 -p 6006:6006  --name tgsandbox --ulimit nofile=1000000:1000000 -v ~/tgsandbox:/home/tigergraph/tgsandbox tigergraphml/sandbox
----

Here is a breakdown of the options in the docker run command above

* `-it`: run the container interactively and allocate a pseudo-TTY.
* `-p`: map a port of the host (14022) to a port of the container (22). Port 22 is for the ssh server, ports 9000 and 14240 are for the database, port 8000 is for GDPS, port 8888 is for jupyterlab, and port 6006 for Tensorboard.
* `--name`: name of the container. Can be any name you like.
* `--ulimit`: the limit of number of open file descriptors per process.
* -v: mount a folder on the host (~/tgsandbox) to a folder in the container (/home/tigergraph/tgsandbox). These two folders are synced and hence allow you to save any file even after the container is removed. However, the folder on the host (~/tgsandbox) has to be writable by the user inside the container. Normally, this can be ensured by making it public, e.g., `chmod 777  ~/tgsandbox`.

After the container has started up, go to the URL in your terminal to access the JupyterLab IDE.

== Video walk-through
Here is a video walk-through of running the sandbox image:

video::7vnxNPWxoVQ[youtube,width=600,height=400]


== Next steps

* xref:tutorials:index.adoc#_train_your_first_model[Train your first model].