= Get started with ML Workbench Sandbox Image
:sectnums:
:description: This page provides instructions on running the ML Workbench from a sandbox Docker image.
:page-aliases: docker.adoc

This page walks you through running the TigerGraph ML Workbench in a Docker container.

To help you get started quickly, we provide a “sandbox” docker image that has the TigerGraph database, GDPS, and ML Workbench pre-installed.
The “Cora” dataset used for tutorials is also preloaded into the database.

== Prerequisites
* You machine needs to meet the xref:tigergraph-server:installation:hw-and-sw-requirements.adoc[].
** Make sure you are allocating enough CPU and memory to your Docker containers.
It is recommended that you allocate at least 8 CPUs and 16 GB of memory to your Docker containers.
* Docker Desktop is running on your machine.

== Procedure

. link:https://info.tigergraph.com/ml-workbench-download[Sign up] for the Workbench preview release.
You will receive an email after signing up that contains the instructions to start a Docker container from the sandbox image.
After the container has started up, JupyterLab will provide you with a URL in your terminal to access the JupyterLab IDE.
Visit the URL in your browser. 
. If you want shell access to your Docker container, run the following command:
+
[.wrap,console]
----
$ ssh -p 14022 tigergraph@localhost
----
When prompted for the password for user `tigergraph`, enter `tigergraph`.
+
Alternatively, if you don't have access to `ssh`, you can get shell access through `docker exec`:
+
[.wrap,console]
----
$ docker exec -it $(docker ps | grep tgsandbox | awk '{print $1}') /bin/sh
----
. If you turn off the sandbox container and start the container again, JupyterLab starts automatically as soon as the container starts.
However, JupyterLab generates a new token everytime it restarts.
You can retrieve the URL with the token by running `docker logs tgsandbox`, or click the container in the Docker Desktop UI to retrieve the URL from the latest terminal output.


== Video walk-through
Here is a video walk-through of running the sandbox image:

video::7vnxNPWxoVQ[youtube,width=700,height=400]


== Next steps

* xref:tutorials:index.adoc#_train_your_first_model[Train your first model].