= Integrate Workbench with Google Vertex AI
:sectnums:
:description:  Instructions for integrating ML Workbench with Google Vertex AI.
:experimental:

This guide walks you through integrating the ML Workbench with a notebook on Google Vertex AI.

== Prerequisite
* A running Google Vertex AI instance

== Procedure
. From the Workbench page in Vertex AI, find your notebook instance and click btn:[OPEN JUPYTERLAB] to navigate to the JupyterLab web interface.
Click menu:File[New > Terminal] to open a terminal.
. From the terminal, run `pip install tigergraph_mlworkbench`.
This installs the ML Workbench JupyterLab extension.
include::partial$install-kernel.adoc[]
. Once installation finishes, refresh your browser.
You should see a small TigerGraph logo on the very left navigation bar and a new Python kernel called TigerGraph Pytorch on the launch page.

== Next steps

With the ML Workbench JupyterLab extension and the `tigergraph-torch` kernel installed, the next step is to xref:deploy-gdps.adoc[deploy GDPS] on your TigerGraph instance so the Workbench can communicate with your TigerGraph database.