= Tutorials
:experimental:

Our tutorials are all written in Jupyter notebooks in the Workbench itself.
Here we provide a brief overview of the tutorial materials as well as a video walk-through of one of the model training tutorials.

== Access tutorials

To access the built-in tutorials, from the Jupyter Lab server page, click menu:File[New Launcher > TigerGraph ML Tutorial].

The dropdown menu gives you a list of tutorials, including tutorials that walk you through how to load and process data in the Workbench, as well as tutorials that walk you through training actual models with Graph Neural Network (GNN) using a sample dataset :

.Data loading and processing
* Data ingestion.
This notebook walks you through how to load the example Cora dataset into your TigerGraph database.
** The dataset contains 2708 machine learning papers and 10556 citation links between the papers.
** Each publication in the dataset is described by a 0/1-valued word vector indicating the absence/presence of the corresponding word from a dictionary.
** The dictionary consists of 1433 unique words.
* Data processing.
This notebook demonstrates how to use xref:tgml:index.adoc[`tgml`] for common data processing tasks on graphs stored in TigerGraph.
* Data loaders.
This notebook demonstrates the use of different data loaders in xref:tgml:index.adoc[`tgml`].
The job of a data loader is to pull data from the TigerGraph database.

.GNN Model Training tutorials
* Graph Convolutional Network (GCN).
This tutorial walks through the training of link:https://arxiv.org/pdf/1609.02907.pdf[Graph Convolutional Networks (GCN)] with TigerGraph.
* GraphSAGE.
This tutorial walks through the training of link:https://arxiv.org/abs/1706.02216[GraphSAGE] models with TigerGraph.
* Graph Attention Network.
This tutorial walks through the training of link:https://arxiv.org/abs/1710.10903[Graph Attention Networks] with TigerGraph.

[#_train_your_first_model]
== Train your first model

You can use any of the training notebooks to guide yourself through the training.
Here we provide a video walk-through of the GraphSAGE tutorial:

.GraphSAGE Tutorial Walk-through
video::ohwYjB_TydM[youtube,800]

