= Set up ML Workbench Enterprise Edition

ML Workbench offers two different communication methods for exporting data from your TigerGraph Database instance to your ML development environment: HTTPS and Kafka streaming.

HTTPS data is limited to 2GB of data export at a time, while Kafka streaming does not have this limitation.
Kafka streaming is only available for the Enterprise Edition.

== Activate ML Workbench

If you have already xref:activate.adoc[activated ML Workbench], no additional setup is required to use the HTTPS method.

If you plan to use Kafka on the Enterprise Edition to stream data out from a TigerGraph database, you need to provide the Kafka credentials so that data can be exported correctly.

The ML Workbench supports the `SASL_PLAIN` authentication method.


== Setting up Kafka

=== Method 1: Setting up Kafka using docker-compose 

1. docker-compose file link:https://github.com/zhixian-tg/mlworkbench-docs/blob/main/modules/on-prem/pages/docker-compose.yaml[docker-compose.yaml]

2. install kafka on your machine / VM
`docker-compose up -d`  
Note: you need to open these ports in the firewall setting: 2181, 19092, 9092 (or whichever port is specified as an external listener)

3. add kafka into your notebook config

`conn.gds.configureKafka(kafka_address="<your-kafka-ip-address>:9092")`


=== Method 2: Setting up Kafka cluster (TODO)

== 
There are several examples in link:https://github.com/TigerGraph-DevLabs/mlworkbench-docs/blob/main/tutorials/basics/3_neighborloader.ipynb[this tutorial] to showcase how to configure the dataloader to work with your Kafka cluster.
