= ML Workbench Standalone Installation
:description: This page provides instructions on running the ML Workbench locally from either a Docker image or on your machine.

If you already have an existing TigerGraph solution locally, you can try out ML Workbench with your own database using a Docker image and a Mac OS or Linux installer.

== Docker image

Docker must be installed and running on your machine.

In the console, run this command:

[source, bash]
----
docker run -it -p 8888:8888 --name mlworkbench -v ~/mlworkbench:/home/tigergraph/save tigergraphml/mlworkbench:1.0.0
----

This command prints the link to the JupyterLab workbench in a format similar to `127.0.0.1:8888/lab?token=`. Use this link in your browser to access the workbench, which is a customized version of JupyterLab.

[NOTE]
If the Docker container is running remotely, open port 8888 on the remote machine to allow the connection. Then replace `127.0.0.1` in the returned address with the remote machine IP address.

== Mac OS installer

. Download the installer at this link: link:https://tg-mlworkbench.s3.us-west-1.amazonaws.com/jupyterlab/MLWorkbench-1.0.0-MacOSX-x86_64.sh[Download MLWorkbench-1.0.0-MacOSX-x86_64.sh]
. Open a Terminal window in the folder where the installer was downloaded.
. Run the command `bash MLWorkbench-1.0.0-MacOSX-x86_64.sh` and follow the prompts to install.

The installation prompt asks whether you want to "initialize."

* If you agree to initialize, it will change your default Python environment to the workbench.
* If you decline, the ML workbench still functions, but you will need to activate the Python environment before going to the JupyterLab.

[start=4]
. Relaunch Terminal for the PATH change to take effect.
. Run the command `jupyter lab` to start. This starts the Jupyter server and opens JupyterLab in your browser.
If you would like to access JupyterLab from a remote browser, type `jupyter lab --ip=0.0.0.0 --no-browser` instead.

JupyterLab only has access to the folder where it is launched. If you need to access files at a different location, launch JupyterLab in that location.

== Linux installer

. Download the installer at this link: link:https://tg-mlworkbench.s3.us-west-1.amazonaws.com/jupyterlab/MLWorkbench-1.0.0-Linux-x86_64.sh[Download MLWorkbench-1.0.0-Linux-x86_64.sh]
. Open the terminal and navigate to where the installer was downloaded.
. Run the command `bash MLWorkbench-1.0.0-Linux-x86_64.sh` and follow the prompts to install.

The installation prompt asks whether you want to "initialize."

* If you agree to initialize, it will change your default Python environment to the workbench.
* If you decline, the ML workbench still functions, but you will need to type the full path of the `jupyter` executable to start it.

[start=4]
. Relaunch the terminal for the PATH change to take effect.
. Run the command `jupyter lab` to start. This starts the Jupyter server and opens JupyterLab in your browser.
If you would like to access JupyterLab from a remote browser, type `jupyter lab --ip=0.0.0.0 --no-browser` instead.

JupyterLab only has access to the folder where it is launched. If you need to access files at a different location, launch JupyterLab in that location.

== Next steps

After installation, the next step is to xref:activate.adoc[].

You can then go to our xref:tutorials:index.adoc[] section.
Follow the instructions, use our tutorials and download our latest notebook examples and data sets there to practice using the ML Workbench.

