= ML Workbench Standalone Installation
:description: This page provides instructions on running the ML Workbench locally from either a Docker image or on your machine.

If you already have an existing TigerGraph solution locally, you can try out ML Workbench with your own database using a Docker image and a Mac OS or Linux installer.

== Docker image

Docker must be installed and running on your machine.

In the console, run this command:

[source, bash]
----
docker run -it -p 8888:8888 --name mlworkbench -v ~/mlworkbench:/home/tigergraph/save tigergraphml/mlworkbench:1.4.0
----

This command prints the link to the JupyterLab workbench in a format similar to `127.0.0.1:8888/lab?token=`. Use this link in your browser to access the workbench, which is a customized version of JupyterLab.

[NOTE]
If the Docker container is running remotely, open port 8888 on the remote machine to allow the connection. Then replace `127.0.0.1` in the returned address with the remote machine IP address.

== Next steps

After installation, the next step is to xref:activate.adoc[].

You can then go to our xref:tutorials:index.adoc[] section.
Follow the instructions, use our tutorials and download our latest notebook examples and data sets there to practice using the ML Workbench.

